name: Run Daily Script

on:
  schedule:
    - cron: '0 6 * * *'  # Täglich um 6:00 UTC (8:00 MEZ)
  workflow_dispatch:  # <-- das hinzufügen

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CITY: ${{ secrets.CITY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
